### ISSUE TITLE
Add Steam authorization

### ISSUE THREAD

**Issue by CuteD0d** [bologer/anycomment.io#311]
Need steam auth

**Comment by bologer** [comment]
@CuteD0d will be added on the upcoming release

**Comment by bologer** [comment]
docs: 

- [ ] en
- [ ] ru

**Comment by bologer** [comment]
Russian docs moved to #324, closing this as implemented. 

Btw, Steam is weird as they do not provide email address of the user due to their terms of services as they think this is privacy and can cause mass spam attacks etc ([source](https://stackoverflow.com/a/31571342/3661795)). WTF. 

I have some bypass: ask user for email after he registered on the website and then confirm it. However this would be implemented a bit later. 

This would be useful also for some other socials where user did not provide email address :+1:
